#!/usr/bin/env python3
"""Checksum vectors for the values a client states about a body.

Written out rather than computed inside a test on purpose: a vector produced by the code it checks
proves the code is deterministic and nothing else. Everything here comes from Python's standard
library, except CRC32C, which the standard library does not have and which is therefore implemented
from the polynomial — an independent implementation of the same specification, not a translation of
the Java one.

    python3 docs/spec/checksums/generate.py > docs/spec/checksums/vectors.txt

Headers: `s3-service-2.json`, `PutObjectRequest.members.ContentMD5` (`Content-MD5`) and
`ChecksumCRC32` / `ChecksumCRC32C` / `ChecksumSHA1` / `ChecksumSHA256` (`x-amz-checksum-*`).
Every value is base64; a CRC is base64 of its four bytes big-endian, not of its decimal text.
"""

import base64
import hashlib
import struct
import zlib

CRC32C_POLYNOMIAL = 0x82F63B78  # Castagnoli, reversed representation
CRC64NVME_POLYNOMIAL = 0x9A6C9329AC4BC9B5  # NVMe / Rocksoft, reversed representation


def crc32c(data: bytes) -> int:
    crc = 0xFFFFFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ (CRC32C_POLYNOMIAL & -(crc & 1))
    return crc ^ 0xFFFFFFFF


def crc64nvme(data: bytes) -> int:
    """CRC-64/NVME. Published check value for b"123456789" is 0xAE8B14860A799888."""
    crc = 0xFFFFFFFFFFFFFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ (CRC64NVME_POLYNOMIAL & -(crc & 1))
    return crc ^ 0xFFFFFFFFFFFFFFFF


def b64_of_uint32(value: int) -> str:
    return base64.b64encode(struct.pack(">I", value)).decode()


def b64_of_uint64(value: int) -> str:
    return base64.b64encode(struct.pack(">Q", value)).decode()


def b64(data: bytes) -> str:
    return base64.b64encode(data).decode()


CASES = [
    ("empty", b""),
    ("testcontent", b"testcontent"),
    ("one-byte-zero", b"\x00"),
    ("high-bytes", bytes(range(256))),
    # The catalogue's check input, so the polynomial and its direction are pinned by a published
    # value rather than by agreement between two implementations that could be wrong together.
    ("check-123456789", b"123456789"),
]

if __name__ == "__main__":
    assert crc64nvme(b"123456789") == 0xAE8B14860A799888, "CRC-64/NVME check value"
    print("# content-name | algorithm | base64")
    print("# generated by docs/spec/checksums/generate.py")
    for name, data in CASES:
        print(f"{name}\tcontent-md5\t{b64(hashlib.md5(data).digest())}")
        print(f"{name}\tx-amz-checksum-crc32\t{b64_of_uint32(zlib.crc32(data) & 0xFFFFFFFF)}")
        print(f"{name}\tx-amz-checksum-crc32c\t{b64_of_uint32(crc32c(data))}")
        print(f"{name}\tx-amz-checksum-crc64nvme\t{b64_of_uint64(crc64nvme(data))}")
        print(f"{name}\tx-amz-checksum-sha1\t{b64(hashlib.sha1(data).digest())}")
        print(f"{name}\tx-amz-checksum-sha256\t{b64(hashlib.sha256(data).digest())}")
