plugins {
    id("org.jetbrains.kotlin.jvm")
    id("ru.workinprogress.sborka.jvm")
    id("ru.workinprogress.sborka.lint")
}

// Publishes nothing and is depended on by nothing: this module exists to point a fuzzer at the
// parsers, and its targets are not a surface anybody consumes.

dependencies {
    // Everything that reads bytes off a socket before anything has been verified. The fuzz targets
    // use the same public entry points a request takes, so a target cannot drift into exercising a
    // path the server does not.
    testImplementation(project(":bochka-core"))
    testImplementation(project(":bochka-s3"))
    testImplementation(project(":bochka-http"))

    testImplementation(kotlin("test"))
    testImplementation(libs.jazzer.junit)
}

// How long one target fuzzes, as a **compile-time** constant, because `@FuzzTest(maxDuration = …)`
// is an annotation argument and nothing read at runtime can change it. Three system properties that
// look like they should were tried and measured: `jazzer.internal.arg.max_total_time`,
// `jazzer.max_duration` and `jazzer.internal.arg.max_duration` all left the run at 61 seconds. So
// the value is generated rather than guessed at through a property that does not exist.
//
// `-Pbochka.fuzzSeconds=1800` is therefore what an overnight run differs by, and a pull request
// and that overnight run are otherwise the same targets and the same corpus.
val fuzzSeconds = (project.findProperty("bochka.fuzzSeconds") as String?) ?: "60"

val generateFuzzDuration =
    tasks.register("generateFuzzDuration") {
        description = "Writes the per-target fuzzing duration as a constant the annotation can take"
        val out = layout.buildDirectory.dir("generated/fuzz")
        inputs.property("seconds", fuzzSeconds)
        outputs.dir(out)
        doLast {
            val file = out.get().file("io/github/youndie/bochka/fuzz/FuzzDuration.kt").asFile
            file.parentFile.mkdirs()
            file.writeText(
                """
                package io.github.youndie.bochka.fuzz

                // Generated by :bochka-fuzz:generateFuzzDuration. Change it with
                // -Pbochka.fuzzSeconds=<n>, not by editing this file.
                const val FUZZ_DURATION = "${fuzzSeconds}s"

                """.trimIndent(),
            )
        }
    }

kotlin.sourceSets.named("test") { kotlin.srcDir(generateFuzzDuration) }

// The generated constant is not source anybody writes, so it is not source anybody formats.
ktlint {
    filter { exclude { it.file.path.contains("/generated/") } }
}

tasks.withType<Test>().configureEach {
    // The repository's runtime profile is `-Xmx64M`, and it is a gate rather than a preference:
    // the hot path is not allowed to need more. A fuzzer is not the hot path. Jazzer installs an
    // agent that scans the whole classpath through ClassGraph, and in 64 MiB that dies with an
    // `OutOfMemoryError` reported as `ArgumentsProvider does not override provideArguments(...)` —
    // a message that reads as a JUnit version conflict and is not one.
    //
    // Hence a heap of its own, and hence this module rather than fuzz targets living beside the
    // ordinary tests: the footprint gate has to keep meaning what it says everywhere else.
    jvmArgs = listOf("-Xmx2G")

    // Where Jazzer puts the corpus it generates. Left alone it writes `.cifuzz-corpus/` beside the
    // module — a path that is neither in the repository nor under `build/`, so nothing owns it,
    // nothing cleans it, and nothing guarantees it survives the run that is writing it. Observed
    // as a run that does 378 000 inputs and then dies on `No such file or directory`, which reads
    // as an unstable tool rather than a homeless directory.
    systemProperty(
        "jazzer.internal.basedir",
        layout.buildDirectory
            .get()
            .asFile.absolutePath,
    )
}
